coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: 80%
        threshold: 1%
ignore:
  - "src/**/*.test.ts"
  - "src/**/*.test.tsx"
  - "src/**/*.stories.tsx"
  - "src/test/**"
