/**
 * Default brand suggestions for complete bicycles (manufacturers / frame builders).
 * Inventory parts use `DEFAULT_BRANDS` in `@/features/inventory/constants`.
 */
export const DEFAULT_BIKE_BRANDS = [
  'All-City',
  'Argon 18',
  'Basso',
  'Bianchi',
  'BMC',
  'Brompton',
  'Cannondale',
  'Canyon',
  'Cervelo',
  'Colnago',
  'Commencal',
  'Cube',
  'Diamondback',
  'Evil',
  'Focus',
  'Fuji',
  'Ghost',
  'Giant',
  'GT',
  'Haibike',
  'Ibis',
  'Juliana',
  'Kona',
  'Lapierre',
  'Look',
  'Marin',
  'Merida',
  'Norco',
  'OPEN',
  'Orbea',
  'Pinarello',
  'Pivot',
  'Polygon',
  'Propain',
  'Radon',
  'Ridley',
  'Rose',
  'Santa Cruz',
  'Scott',
  'Specialized',
  'Surly',
  'Trek',
  'Transition',
  'Vitus',
  'Wilier',
  'Yeti',
  'YT Industries',
] as const;
