import type { ItemCategory } from '@/shared/types';
import { ItemCategory as ItemCategoryEnum } from '@/shared/types';

/**
 * Subcategories grouped by parent category.
 * Keys are ItemCategory values, values are arrays of subcategory keys
 * that map to i18n strings at `subcategory.<key>`.
 */
export const SUBCATEGORIES: Record<ItemCategory, readonly string[]> = {
  [ItemCategoryEnum.Component]: [
    'drivetrain',
    'brakes',
    'wheels',
    'tires_tubes',
    'handlebars_stems',
    'seatposts_saddles',
    'suspension',
    'frames',
    'headsets_bearings',
    'pedals',
    'bottom_brackets',
    'cables_housing',
    'other_component',
  ],
  [ItemCategoryEnum.Tool]: [
    'multi_tools',
    'wrenches',
    'chain_tools',
    'tire_levers',
    'pumps',
    'torque_wrenches',
    'stands',
    'cleaning',
    'measurement',
    'other_tool',
  ],
  [ItemCategoryEnum.Accessory]: [
    'lights',
    'locks',
    'bags_racks',
    'fenders',
    'bottles_cages',
    'computers_gps',
    'cameras',
    'bells_mirrors',
    'other_accessory',
  ],
  [ItemCategoryEnum.Consumable]: [
    'chain_lube',
    'grease',
    'degreaser',
    'brake_fluid',
    'tubeless_sealant',
    'thread_locker',
    'anti_seize',
    'polish',
    'other_consumable',
  ],
  [ItemCategoryEnum.Clothing]: [
    'jerseys',
    'shorts_bibs',
    'jackets_vests',
    'gloves',
    'socks',
    'shoes',
    'helmets',
    'eyewear',
    'base_layers',
    'arm_leg_warmers',
    'rain_gear',
    'knee_pads',
    'elbow_pads',
    'body_armor',
    'reflective_gear',
    'other_protective_gear',
    'other_clothing',
  ],
  [ItemCategoryEnum.Bike]: [],
} as const;

/**
 * Icons for subcategories using MaterialCommunityIcons names.
 */
export const SUBCATEGORY_ICONS: Record<string, string> = {
  // Components
  drivetrain: 'cog',
  brakes: 'car-brake-alert',
  wheels: 'tire',
  tires_tubes: 'circle-outline',
  handlebars_stems: 'steering',
  seatposts_saddles: 'seat',
  suspension: 'arrow-collapse-vertical',
  frames: 'triangle-outline',
  headsets_bearings: 'circle-double',
  pedals: 'shoe-print',
  bottom_brackets: 'cog-outline',
  cables_housing: 'cable-data',
  other_component: 'dots-horizontal',
  // Tools
  multi_tools: 'wrench',
  wrenches: 'wrench-outline',
  chain_tools: 'link-variant',
  tire_levers: 'arrow-up-bold',
  pumps: 'air-filter',
  torque_wrenches: 'speedometer',
  stands: 'tools',
  cleaning: 'spray-bottle',
  measurement: 'ruler',
  other_tool: 'dots-horizontal',
  // Accessories
  lights: 'flashlight',
  locks: 'lock',
  bags_racks: 'bag-personal',
  fenders: 'shield-half-full',
  bottles_cages: 'bottle-soda-outline',
  computers_gps: 'monitor-dashboard',
  cameras: 'camera',
  bells_mirrors: 'bell',
  other_accessory: 'dots-horizontal',
  // Consumables
  chain_lube: 'oil',
  grease: 'oil-lamp',
  degreaser: 'bottle-tonic',
  brake_fluid: 'water',
  tubeless_sealant: 'seal',
  thread_locker: 'lock-outline',
  anti_seize: 'shield-outline',
  polish: 'auto-fix',
  other_consumable: 'dots-horizontal',
  // Clothing
  jerseys: 'tshirt-crew',
  shorts_bibs: 'lingerie',
  jackets_vests: 'coat-rack',
  gloves: 'hand-back-left',
  socks: 'shoe-formal',
  shoes: 'shoe-sneaker',
  helmets: 'hard-hat',
  eyewear: 'sunglasses',
  base_layers: 'tshirt-crew-outline',
  arm_leg_warmers: 'arm-flex',
  rain_gear: 'weather-rainy',
  knee_pads: 'shield-lock',
  elbow_pads: 'shield-lock-outline',
  body_armor: 'shield',
  reflective_gear: 'reflect-vertical',
  other_protective_gear: 'shield-outline',
  other_clothing: 'dots-horizontal',
};

/**
 * Default brand suggestions for inventory items (parts, accessories, consumables).
 * Complete-bike suggestions: `DEFAULT_BIKE_BRANDS` in `@/features/bikes/constants`.
 * Users can always enter a brand that is not in the list.
 */
export const DEFAULT_BRANDS = [
  'Shimano',
  'SRAM',
  'Campagnolo',
  'Continental',
  'Schwalbe',
  'Mavic',
  'DT Swiss',
  'Park Tool',
  'Topeak',
  'Brooks',
  'Fizik',
  'FSA',
  'Chris King',
  'Hope',
  'Magura',
  'TRP',
  'Zipp',
  'Enve',
  'Thomson',
  'Ritchey',
  'Bontrager',
  'Giant',
  'Specialized',
  'Trek',
  'Cannondale',
  'Canyon',
  'Santa Cruz',
  'Crank Brothers',
  'Look',
  'SKS',
  'Lezyne',
  'Knog',
  'Ortlieb',
  'Thule',
  'Wahoo',
  'Garmin',
  'GoPro',
  'Insta360',
  'DJI',
  'Sony',
  'Canon',
  'Nikon',
  'Cycliq',
  'Akaso',
  'Drift',
  'RockShox',
  'Fox',
  'Maxxis',
  'Vittoria',
  'WTB',
  'Race Face',
  'Ergon',
  'PRO',
  'Deda',
  'Cinelli',
  '3T',
  'Rotor',
  'Stages',
  'Quarq',
  'Muc-Off',
  'Finish Line',
  "Pedro's",
  'Motorex',
  'Squirt',
  'Silca',
  "Stan's NoTubes",
  'Loctite',
] as const;

/** Thumbnail size for inventory list rows and gallery tiles (keep in sync). */
export const ITEM_INVENTORY_THUMBNAIL = {
  width: 80,
  height: 60,
} as const;

/**
 * Predefined age options for selector.
 * Values are i18n keys under `form.ageOption.<key>`.
 */
export const AGE_OPTIONS = [
  'less_than_6_months',
  '6_to_12_months',
  '1_to_2_years',
  '2_to_3_years',
  '3_to_5_years',
  '5_to_10_years',
  'over_10_years',
] as const;

// DURATION_OPTIONS and DistanceUnit moved to @/shared/types/enums.ts
export { DURATION_OPTIONS, DistanceUnit } from '@/shared/types';
